# numpy - array, shape, dtype

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array 1 = ', array1)
print('array 1 type = ', type(array1))

array 1 =  [1 2 3]
array 1 type =  <class 'numpy.ndarray'>


In [4]:
print('array 1 shape = ', array1.shape)

array 1 shape =  (3,)


In [5]:
list = [[1,2,3], [4,5,6]]
array2 = np.array(list)
print('array 2 = ', array2)
print('array 2 shape = ', array2.shape)

array 2 =  [[1 2 3]
 [4 5 6]]
array 2 shape =  (2, 3)


In [6]:
array3 = np.array([[1,2,3]])
print('array 3 = ', array3)
print('array 3 shape = ', array3.shape)

array 3 =  [[1 2 3]]
array 3 shape =  (1, 3)


In [9]:
print('array 1 : {0} dimension, array 2 : {1} dimension, array 3 : {2} dimension'.format(array1.ndim, array2.ndim, array3.ndim))

array 1 : 1 dimension, array 2 : 2 dimension, array 3 : 2 dimension


In [11]:
list_type = [1,2,3.0]
array_type = np.array(list_type)
print(array_type, 'data type : ', array_type.dtype)

[1. 2. 3.] data type :  float64


In [12]:
array_type = array_type.astype('int32')
print('array_type data type : ', array_type.dtype)

array_type data type :  int32


# arange, zeros, ones

In [13]:
print('ex 1 : ', np.arange(10))

ex 1 :  [0 1 2 3 4 5 6 7 8 9]


In [14]:
print('ex 2 : ', np.arange(3,10))

ex 2 :  [3 4 5 6 7 8 9]


In [15]:
print('ex 3 : ', np.arange(1, 10, 2))

ex 3 :  [1 3 5 7 9]


In [16]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print('data shape : ', zero_array.shape)
print('data tyep : ', zero_array.dtype)

[[0 0]
 [0 0]
 [0 0]]
data shape :  (3, 2)
data tyep :  int32


In [17]:
one_array = np.ones((3, 2))
print(one_array)
print('data shape : ', one_array.shape)
print('data type : ', one_array.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
data shape :  (3, 2)
data type :  float64


In [20]:
array = np.arange(10)
print('array : \n', array)
array1 = array.reshape(2,5)
print('array1 : \n', array1)
array2 = array.reshape(5,2)
print('array2 : \n', array2)

array : 
 [0 1 2 3 4 5 6 7 8 9]
array1 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
array3 = array.reshape(-1, 2)
print('array3 shape : ', array3.shape)
array4 = array.reshape(2, -1)
print('array4 shape : ', array4.shape)

array3 shape :  (5, 2)
array4 shape :  (2, 5)


In [22]:
array5 = array.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [23]:
array = np.arange(1, 10)
print('array : ', array)
print('3rd element in array : ', array[2])
print('2nd element data type : ', type(array[1]))

array :  [1 2 3 4 5 6 7 8 9]
3rd element in array :  3
2nd element data type :  <class 'numpy.int64'>


In [25]:
print('array[1:4] : ', array[1:4])
print('data type : ', type(array[1:4]))

array[1:4] :  [2 3 4]
data type :  <class 'numpy.ndarray'>


In [26]:
print(array[:6])
print(array[2:])
print(array[:])

[1 2 3 4 5 6]
[3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [27]:
array = array.reshape(3,3)
print('array : \n', array)
print('array[0:2, 0:2] : \n', array[0:2, 0:2])
print('array[1:3, :] : \n', array[1:3, :])
print('array[:2, 1:] : \n', array[:2, 1:])

array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array[0:2, 0:2] : 
 [[1 2]
 [4 5]]
array[1:3, :] : 
 [[4 5 6]
 [7 8 9]]
array[:2, 1:] : 
 [[2 3]
 [5 6]]


In [30]:
print('array : \n', array)
print('array[[0,2], :] : \n', array[[0,2], :])
print('array[[0,2]] : \n', array[[0,2]])
print('array[[0,2], 1:] : \n', array[[0,2], 1:])

array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array[[0,2], :] : 
 [[1 2 3]
 [7 8 9]]
array[[0,2]] : 
 [[1 2 3]
 [7 8 9]]
array[[0,2], 1:] : 
 [[2 3]
 [8 9]]


In [32]:
array = np.arange(1, 10)
array1 = array[array > 4]
array2 = array[(2 <= array) & (array < 7)]

print('array : ', array)
print('array1 : ', array1)
print('array2 : ', array2)

array :  [1 2 3 4 5 6 7 8 9]
array1 :  [5 6 7 8 9]
array2 :  [2 3 4 5 6]


In [33]:
original_array = np.array([3,1,9,5])
print('original : ', original_array)

original :  [3 1 9 5]


In [34]:
sort_array1 = np.sort(original_array)
print('np.sort() -> : ', sort_array1)
print('original : ', original_array)

np.sort() -> :  [1 3 5 9]
original :  [3 1 9 5]


In [35]:
sort_array2 = original_array.sort()
print('original_array.sort() : ', sort_array2)
print('original : ', original_array)

original_array.sort() :  None
original :  [1 3 5 9]


In [36]:
print('decrease : ', np.sort(original_array)[::-1])

decrease :  [9 5 3 1]


In [37]:
array = np.array([[8, 12], [7, 1]])
sort_array_axis0 = np.sort(array, axis = 0)
print('row sort : ', sort_array_axis0)

sort_array_axis1 = np.sort(array, axis = 1)
print('col sort : ', sort_array_axis1)

row sort :  [[ 7  1]
 [ 8 12]]
col sort :  [[ 8 12]
 [ 1  7]]


In [40]:
original_array = np.array([3,1,9,5])
original_index = np.argsort(original_array)
print('index of sorted array : ', original_index)
print('type of index : ', type(original_index))

index of sorted array :  [1 0 3 2]
type of index :  <class 'numpy.ndarray'>


In [41]:
print('array sort using argsort : ', original_array[original_index])

array sort using argsort :  [1 3 5 9]


In [42]:
name_array = np.array(['john', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78, 95, 84, 98, 88])
score_index = np.argsort(score_array)[::-1]
print('score index : ', score_index)
print('high score order : ', name_array[score_index])

score index :  [3 1 4 2 0]
high score order :  ['kate' 'mike' 'samuel' 'sarah' 'john']


In [45]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
print('dot : \n', np.dot(A,B))

dot : 
 [[ 58  64]
 [139 154]]


In [46]:
A = np.array([[1,2], [3,4]])
print('A transpose : \n', np.transpose(A))

A transpose : 
 [[1 3]
 [2 4]]


# pandas
### index, series, dataframe

In [47]:
import pandas as pd

In [53]:
titanic_df = pd.read_csv('data/titanic.csv')
print('titanic variable type : ', type(titanic_df))
titanic_df

titanic variable type :  <class 'pandas.core.frame.DataFrame'>


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [54]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S


In [55]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [56]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [57]:
titanic_pclass = titanic_df['Pclass']
print('titanic_df[Pclass] data type : ', type(titanic_pclass))
titanic_pclass.head()

titanic_df[Pclass] data type :  <class 'pandas.core.series.Series'>


0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [59]:
print('value_counts return value data type : ', type(titanic_pclass.value_counts()))
print(titanic_pclass.value_counts())

value_counts return value data type :  <class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [60]:
col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
df_list1 = pd.DataFrame(list1, columns = col_name1)
print('DataFrame made of 1 dim list : \n', df_list1)
df_array1 = pd.DataFrame(array1, columns = col_name1)
print('DatFrame made of 1 dim ndarray : \n', df_array1)

DataFrame made of 1 dim list : 
    col1
0     1
1     2
2     3
DatFrame made of 1 dim ndarray : 
    col1
0     1
1     2
2     3


In [62]:
list2 = [[1,2,3], [4,5,6]]
array2 = np.array(list2)
print("array2's shape : ", array2.shape)
col_name2 = ['col1', 'col2', 'col3']
df_list2 = pd.DataFrame(list2, columns = col_name2)
df_array2 = pd.DataFrame(array2, columns = col_name2)
print('DataFrame made of 2 dim list : \n', df_list2)
print('DataFrame made of 2 dim ndarray :\n', df_array2)

array2's shape :  (2, 3)
DataFrame made of 2 dim list : 
    col1  col2  col3
0     1     2     3
1     4     5     6
DataFrame made of 2 dim ndarray :
    col1  col2  col3
0     1     2     3
1     4     5     6


In [63]:
dict = {'col1' : [1,4], 'col2' : [2,5], 'col3' : [3,6]}
df_dict = pd.DataFrame(dict)
print('DataFrame made of dict : \n', df_dict)

DataFrame made of dict : 
    col1  col2  col3
0     1     2     3
1     4     5     6


In [64]:
array3 = df_array2.values

In [66]:
print('df_array2.values type : ', type(array3))
print('df_array2.values shape : ', array3.shape)
print(array3)

df_array2.values type :  <class 'numpy.ndarray'>
df_array2.values shape :  (2, 3)
[[1 2 3]
 [4 5 6]]


In [68]:
list3 = df_list2.values.tolist()
print('df_list2.values.tolist() type', type(list3))
print(list3)

df_list2.values.tolist() type <class 'list'>
[[1, 2, 3], [4, 5, 6]]


In [70]:
dict3 = df_dict.to_dict('list')
print("df_dict.to_dict('list') type : ", type(dict3))
print(dict3)

df_dict.to_dict('list') type :  <class 'dict'>
{'col1': [1, 4], 'col2': [2, 5], 'col3': [3, 6]}


In [71]:
titanic_df['Age_0'] = 0
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0


In [72]:
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1


In [73]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1


In [74]:
titanic_drop_df = titanic_df.drop('Age_0', axis = 1)
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1


In [75]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1


In [76]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis = 1, inplace = True)
print('inplace = True return after drop : ', drop_result)
titanic_df.head(3)

inplace = True return after drop :  None


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S


In [77]:
titanic_df = titanic_df.drop('Pclass', axis = 1, inplace = True)
titanic_df.head(3)

AttributeError: 'NoneType' object has no attribute 'head'

In [78]:
titanic_df = pd.read_csv('data/titanic.csv')
print(titanic_df.index)
print('index object array value : \n', titanic_df.index.values)

RangeIndex(start=0, stop=891, step=1)
index object array value : 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 

In [ ]:
indexes = titanic_df.index
print(type(indexes.values))
print(