# numpy - array, shape, dtype

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array 1 = ', array1)
print('array 1 type = ', type(array1))

array 1 =  [1 2 3]
array 1 type =  <class 'numpy.ndarray'>


In [4]:
print('array 1 shape = ', array1.shape)

array 1 shape =  (3,)


In [5]:
list = [[1,2,3], [4,5,6]]
array2 = np.array(list)
print('array 2 = ', array2)
print('array 2 shape = ', array2.shape)

array 2 =  [[1 2 3]
 [4 5 6]]
array 2 shape =  (2, 3)


In [6]:
array3 = np.array([[1,2,3]])
print('array 3 = ', array3)
print('array 3 shape = ', array3.shape)

array 3 =  [[1 2 3]]
array 3 shape =  (1, 3)


In [9]:
print('array 1 : {0} dimension, array 2 : {1} dimension, array 3 : {2} dimension'.format(array1.ndim, array2.ndim, array3.ndim))

array 1 : 1 dimension, array 2 : 2 dimension, array 3 : 2 dimension


In [11]:
list_type = [1,2,3.0]
array_type = np.array(list_type)
print(array_type, 'data type : ', array_type.dtype)

[1. 2. 3.] data type :  float64


In [12]:
array_type = array_type.astype('int32')
print('array_type data type : ', array_type.dtype)

array_type data type :  int32


# arange, zeros, ones

In [13]:
print('ex 1 : ', np.arange(10))

ex 1 :  [0 1 2 3 4 5 6 7 8 9]


In [14]:
print('ex 2 : ', np.arange(3,10))

ex 2 :  [3 4 5 6 7 8 9]


In [15]:
print('ex 3 : ', np.arange(1, 10, 2))

ex 3 :  [1 3 5 7 9]


In [16]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print('data shape : ', zero_array.shape)
print('data tyep : ', zero_array.dtype)

[[0 0]
 [0 0]
 [0 0]]
data shape :  (3, 2)
data tyep :  int32


In [17]:
one_array = np.ones((3, 2))
print(one_array)
print('data shape : ', one_array.shape)
print('data type : ', one_array.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
data shape :  (3, 2)
data type :  float64


In [20]:
array = np.arange(10)
print('array : \n', array)
array1 = array.reshape(2,5)
print('array1 : \n', array1)
array2 = array.reshape(5,2)
print('array2 : \n', array2)

array : 
 [0 1 2 3 4 5 6 7 8 9]
array1 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
array3 = array.reshape(-1, 2)
print('array3 shape : ', array3.shape)
array4 = array.reshape(2, -1)
print('array4 shape : ', array4.shape)

array3 shape :  (5, 2)
array4 shape :  (2, 5)


In [22]:
array5 = array.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [23]:
array = np.arange(1, 10)
print('array : ', array)
print('3rd element in array : ', array[2])
print('2nd element data type : ', type(array[1]))

array :  [1 2 3 4 5 6 7 8 9]
3rd element in array :  3
2nd element data type :  <class 'numpy.int64'>


In [25]:
print('array[1:4] : ', array[1:4])
print('data type : ', type(array[1:4]))

array[1:4] :  [2 3 4]
data type :  <class 'numpy.ndarray'>


In [26]:
print(array[:6])
print(array[2:])
print(array[:])

[1 2 3 4 5 6]
[3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [27]:
array = array.reshape(3,3)
print('array : \n', array)
print('array[0:2, 0:2] : \n', array[0:2, 0:2])
print('array[1:3, :] : \n', array[1:3, :])
print('array[:2, 1:] : \n', array[:2, 1:])

array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array[0:2, 0:2] : 
 [[1 2]
 [4 5]]
array[1:3, :] : 
 [[4 5 6]
 [7 8 9]]
array[:2, 1:] : 
 [[2 3]
 [5 6]]


In [30]:
print('array : \n', array)
print('array[[0,2], :] : \n', array[[0,2], :])
print('array[[0,2]] : \n', array[[0,2]])
print('array[[0,2], 1:] : \n', array[[0,2], 1:])

array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array[[0,2], :] : 
 [[1 2 3]
 [7 8 9]]
array[[0,2]] : 
 [[1 2 3]
 [7 8 9]]
array[[0,2], 1:] : 
 [[2 3]
 [8 9]]


In [32]:
array = np.arange(1, 10)
array1 = array[array > 4]
array2 = array[(2 <= array) & (array < 7)]

print('array : ', array)
print('array1 : ', array1)
print('array2 : ', array2)

array :  [1 2 3 4 5 6 7 8 9]
array1 :  [5 6 7 8 9]
array2 :  [2 3 4 5 6]


In [33]:
original_array = np.array([3,1,9,5])
print('original : ', original_array)

original :  [3 1 9 5]


In [34]:
sort_array1 = np.sort(original_array)
print('np.sort() -> : ', sort_array1)
print('original : ', original_array)

np.sort() -> :  [1 3 5 9]
original :  [3 1 9 5]


In [35]:
sort_array2 = original_array.sort()
print('original_array.sort() : ', sort_array2)
print('original : ', original_array)

original_array.sort() :  None
original :  [1 3 5 9]


In [36]:
print('decrease : ', np.sort(original_array)[::-1])

decrease :  [9 5 3 1]


In [37]:
array = np.array([[8, 12], [7, 1]])
sort_array_axis0 = np.sort(array, axis = 0)
print('row sort : ', sort_array_axis0)

sort_array_axis1 = np.sort(array, axis = 1)
print('col sort : ', sort_array_axis1)

row sort :  [[ 7  1]
 [ 8 12]]
col sort :  [[ 8 12]
 [ 1  7]]


In [40]:
original_array = np.array([3,1,9,5])
original_index = np.argsort(original_array)
print('index of sorted array : ', original_index)
print('type of index : ', type(original_index))

index of sorted array :  [1 0 3 2]
type of index :  <class 'numpy.ndarray'>


In [41]:
print('array sort using argsort : ', original_array[original_index])

array sort using argsort :  [1 3 5 9]


In [42]:
name_array = np.array(['john', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78, 95, 84, 98, 88])
score_index = np.argsort(score_array)[::-1]
print('score index : ', score_index)
print('high score order : ', name_array[score_index])

score index :  [3 1 4 2 0]
high score order :  ['kate' 'mike' 'samuel' 'sarah' 'john']


In [45]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
print('dot : \n', np.dot(A,B))

dot : 
 [[ 58  64]
 [139 154]]
